openapi: 3.0.3
info:
  title: Address
  contact:
    name: CIP Insights & Reputation Team
    email: cip-insights-and-reputation-g@digital.hmrc.gov.uk
  version: '1.0'
  description: >
    # Overview

    ### Address

    This API enables your application to validate and/or get an opinion of the riskiness of an address.
    
    For lookup, the response will provide 0 or more matching addresses.

    For insights, given an address, the response will provide:

    * Risk score from 0 (no risk) to 100 (high risk)
    * Reason providing an indication of why the risk score has been allocated
    * Correlation Id - so you can reference the transaction in any feedback
servers:
  - url: https://test-api.service.hmrc.gov.uk/misc/address
    description: Sandbox
  - url: https://api.service.hmrc.gov.uk/misc/address
    description: Production
paths:
  /lookup:
    post:
      summary: Lookup address
      description: >
        Lookup of postal and BFPO (British Forces Post Office) address details within the UK
      operationId: AddressVerificationLookup
      security:
        - applicationRestricted: [ ]
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: 'docs/lookup-request.json'
            example:
              postcode: "AA1 1ZZ"
              filter: "The Rectory"
        required: true
      responses:
        '200':
          description: ''
          headers: { }
          content:
            application/json:
              schema:
                $ref: 'docs/uk-address-response.json'
              example:
                id: GB200000706253
                uprn: 200000706253
                parentUprn: 200000706251
                usrn: 300000706253
                organisation: Some Company
                address:
                  lines:
                  - Test House
                  - The Tests
                  town: Test Town
                  postcode: BB00 0BB
                  subdivision:
                    code: GB-ENG
                    name: England
                  country:
                    code: GB
                    name: United Kingdom
                localCustodian:
                  code: 1760
                  name: Test Valley
                location:
                - 50.9986451
                - -1.4690977
                language: en
                administrativeArea: TEST COUNTY                ]
        3XX:
          description: |
            The request has been redirected. Clients should follow the redirect using the location header as per the HTTP specification.
        400:
          description: |
            The request was invalid, e.g the postcode is not well formed.
        5XX:
          description: |
            An unexpected server error occurred when processing the request. These are usually temporary and consumers should try again.
      deprecated: false
  /store:
    post:
      summary: Address risk
      description: >
        Store the given address for short term
      operationId: AddressCache
      security:
        - applicationRestricted: [ ]
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: 'docs/risk-insights-request.json'
            example:
              address:
                line1: "1 High Street"
                postcode: "EC1 2FG"
                country: "United Kingdom"
        required: true
      responses:
        '204':
          description: ''
          headers: { }
      deprecated: false
  /risk:
    post:
      summary: Address risk
      description: >
        Check if the provided address is valid
      operationId: AddressRisk
      security:
        - applicationRestricted: [ ]
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: 'docs/risk-insights-request.json'
            example:
              address:
                line1: "1 High Street"
                postcode: "EC1 2FG"
                country: "United Kingdom"
        required: true
      responses:
        '200':
          description: ''
          headers: { }
          content:
            application/json:
              schema:
                $ref: 'docs/risk-response.json'
              example:
                correlationId: "c33b596c-2cdd-4bf7-a20c-8efd1b32802f"
                address:
                  line1: "1 High Street"
                  postcode: "EC1 2FG"
                  country: "United Kingdom"
                insights:
                  risk:
                    riskScore: 0
                    reason: "ADDRESS_NOT_ON_WATCH_LIST"
      deprecated: false
  /insights:
    post:
      summary: Address insights
      description: >
        Check if the provided address is valid
      operationId: AddressInsights
      security:
        - applicationRestricted: [ ]
      parameters: [ ]
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: 'docs/risk-insights-request.json'
            example:
              address:
                line1: "1 High Street"
                postcode: "EC1 2FG"
                country: "United Kingdom"
        required: true
      responses:
        '200':
          description: ''
          headers: { }
          content:
            application/json:
              schema:
                $ref: 'docs/insights-response.json'
              example:
                correlationId: "c33b596c-2cdd-4bf7-a20c-8efd1b32802f"
                address:
                  line1: "1 High Street"
                  postcode: "EC1 2FG"
                  country: "United Kingdom"
                insights:
                  risk:
                    riskScore: 0
                    reason: "ADDRESS_NOT_ON_WATCH_LIST"
                  relationships:
                    occurrences:
                      - event_type: "SARegistration"
                        involvement_group: "sa-reg"
                        involvement_index: 1
                        request_id: "some-request-uuid"
                        session_id: "some-session-uuid"
                        user_id: "joe-bloggs"
                        event_time: "2024-09-17T05:07:23.123"
                      - event_type: "SARegistration"
                        involvement_group: "sa-reg"
                        involvement_index: 2
                        request_id: "some-other-request-uuid"
                        session_id: "some-other-session-uuid"
                        user_id: "joe-bloggs"
                        event_time: "2024-09-17T05:07:29.321"

      deprecated: false
components:
  securitySchemes:
    applicationRestricted:
      type: oauth2
      description: |
        HMRC supports OAuth 2.0 for authenticating application restricted API requests using an OAuth 2.0 Bearer Token in the AUTHORIZATION header.
        See https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/application-restricted-endpoints for details.
      flows:
        clientCredentials:
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          scopes: { }
