openapi: 3.0.3
info:
  title: Address
  contact:
    name: CIP Insights & Reputation Team
    email: cip-insights-and-reputation-g@digital.hmrc.gov.uk
  version: '1.0'
  description: >
    # Overview

    ### Address

    This API enables your application to validate and/or get insights for an address.
    
    For lookup, the response will provide 0 or more matching addresses.

    For reputation, given an address, the response will provide:

    * Assessment with an action and reasons for this action
    * Insights including watchlist check results and occurrences grouped by uprn, locationRef and postcode
    * Correlation Id - so you can reference the transaction in any feedback
servers:
  - url: https://test-api.service.hmrc.gov.uk/misc/address
    description: Sandbox
  - url: https://api.service.hmrc.gov.uk/misc/address
    description: Production
paths:
  /lookup:
    post:
      summary: Lookup address
      description: >
        Lookup of postal and BFPO (British Forces Post Office) address details within the UK
      operationId: AddressVerificationLookup
      security:
        - applicationRestricted: [ ]
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: 'docs/uk-address-lookup-request.json'
            example:
              postcode: "AA1 1ZZ"
              filter: "The Rectory"
        required: true
      responses:
        '200':
          description: ''
          headers: { }
          content:
            application/json:
              schema:
                $ref: 'docs/uk-address-response.json'
              example:
                id: GB200000706253
                uprn: 200000706253
                parentUprn: 200000706251
                usrn: 300000706253
                organisation: Some Company
                address:
                  lines:
                  - Test House
                  - The Tests
                  town: Test Town
                  postcode: BB00 0BB
                  subdivision:
                    code: GB-ENG
                    name: England
                  country:
                    code: GB
                    name: United Kingdom
                localCustodian:
                  code: 1760
                  name: Test Valley
                location:
                - 50.9986451
                - -1.4690977
                language: en
                administrativeArea: TEST COUNTY                ]
        3XX:
          description: |
            The request has been redirected. Clients should follow the redirect using the location header as per the HTTP specification.
        400:
          description: |
            The request was invalid, e.g the postcode is not well formed.
        5XX:
          description: |
            An unexpected server error occurred when processing the request. These are usually temporary and consumers should try again.
      deprecated: false
  /cache:
    post:
      summary: Address risk
      description: >
        Store the given address for short term
      operationId: AddressCache
      security:
        - applicationRestricted: [ ]
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: 'docs/risk-request.json'
            example:
              address:
                addressLine1: "1 High Street"
                postcode: "EC1 2FG"
                country: "United Kingdom"
        required: true
      responses:
        '204':
          description: ''
          headers: { }
      deprecated: false
  /reputation/sa-reg:
    post:
      summary: Address reputation for sa-reg
      description: >
        Provide reputation insights for the given address
      operationId: AddressReputation
      security:
        - applicationRestricted: [ ]
      parameters: [ ]
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: 'docs/reputation-sa-reg-request.json'
            example:
              address:
                addressLine1: "1 High Street"
                postcode: "EC1 2FG"
                country: "United Kingdom"
        required: true
      responses:
        '200':
          description: ''
          headers: { }
          content:
            application/json:
              schema:
                $ref: 'docs/reputation-sa-reg-response.json'
              example:
                correlationId: "c33b596c-2cdd-4bf7-a20c-8efd1b32802f"
                address:
                  addressLine1: "1 High Street"
                  postcode: "EC1 2FG"
                  country: "United Kingdom"
                lookbackDays: 120
                reputation:
                  assessment:
                    action: "CHECK"
                    reasons:
                      - "LOCATION_REF_THRESHOLD_COUNT_BREACHED"
                      - "POSTCODE_THRESHOLD_COUNT_BREACHED"
                insights:
                  relationships:
                    occurrences:
                      byUprn:
                        addresses:
                        count: 0
                      byLocationRef:
                        addresses:
                          - addressLine1: "1 High Street"
                            postcode: "EC1 2FG"
                            country: "United Kingdom"
                            eventType: "SARegistration"
                            addressContext: "home_address_1"
                            requestId: "some-request-uuid"
                            sessionId: "some-session-uuid"
                            userId: "joe-bloggs"
                            eventTime: "2024-09-17T05:07:23.123"
                          - addressLine1: "1 High Road"
                            postcode: "EC1 2FF"
                            country: "United Kingdom"
                            eventType: "SARegistration"
                            addressContext: "home_address_2"
                            requestId: "some-other-request-uuid"
                            sessionId: "some-other-session-uuid"
                            userId: "joe-bloggs"
                            eventTime: "2024-09-17T05:07:29.321"
                        count: 2
                      byPostCode:
                        addresses:
                          - addressLine1: "1 High Street"
                            postcode: "EC1 2FG"
                            country: "United Kingdom"
                            eventType: "SARegistration"
                            addressContext: "home_address_1"
                            requestId: "some-request-uuid"
                            sessionId: "some-session-uuid"
                            userId: "joe-bloggs"
                            eventTime: "2024-09-17T05:07:23.123"
                        count: 1

      deprecated: false
components:
  securitySchemes:
    applicationRestricted:
      type: oauth2
      description: |
        HMRC supports OAuth 2.0 for authenticating application restricted API requests using an OAuth 2.0 Bearer Token in the AUTHORIZATION header.
        See https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/application-restricted-endpoints for details.
      flows:
        clientCredentials:
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          scopes: { }
